# Generated by Django 3.0.3 on 2020-09-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('think_bank', '0002_auto_20200930_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
