# Generated by Django 3.0.3 on 2020-10-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('think_bank', '0002_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='from_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='owner_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='reposts_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='views_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vkuser',
            name='user_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
