# Generated by Django 3.0.3 on 2020-10-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('think_bank', '0004_auto_20201002_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='VkUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('user_img', models.CharField(default='Не указано', max_length=300)),
                ('user_name', models.CharField(default='Не указано', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='VkUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField(default=0)),
                ('viewer_id', models.IntegerField(default=0)),
            ],
        ),
    ]
