# Generated by Django 3.0.3 on 2020-10-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('think_bank', '0004_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_added',
            field=models.CharField(default='', max_length=200),
        ),
    ]
