# Generated by Django 3.0.3 on 2020-10-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('think_bank', '0005_vkuser_vkuserpermissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField(default=0)),
                ('user_id', models.IntegerField(default=0)),
                ('user_img', models.CharField(default='Не указано', max_length=300)),
                ('user_name', models.CharField(default='Не указано', max_length=300)),
                ('comment', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
