# Generated by Django 3.0.3 on 2020-10-10 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('think_bank', '0006_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='vkuserpermissions',
            name='owner_id',
        ),
        migrations.RemoveField(
            model_name='vkuserpermissions',
            name='viewer_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_owner', to='think_bank.VkUser'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vkuser_id', to='think_bank.VkUser'),
        ),
        migrations.AddField(
            model_name='vkuser',
            name='token',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='vkuserpermissions',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='think_bank.VkUser'),
        ),
        migrations.AddField(
            model_name='vkuserpermissions',
            name='viewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewer', to='think_bank.VkUser'),
        ),
    ]
